version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    environment:
      - NEXT_PUBLIC_GATEWAY=http://krakend:8080/
    image: web:latest

  post-service:
    container_name: post-service
    build:
      context: .
      dockerfile: ./apps/post-service/Dockerfile
    restart: always
    ports:
      - 8081:8081
    networks: 
      - app_network
    image: post-service:latest

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    restart: always
    ports:
      - 8082:8082
    networks: 
      - app_network
    image: user-service:latest

  krakend:
    container_name: krakend
    build:
      context: ./krakend
      dockerfile: ./Dockerfile
    image: krakend:latest
    ports:
      - 8080:8080
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
