version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    networks:
      - app_network

  krakend:
    container_name: krakend
    build:
      context: ./krakend
      dockerfile: ./Dockerfile
    image: krakend:latest
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    networks:
      - app_network

  post-service:
    container_name: post-service
    build:
      context: .
      dockerfile: ./apps/post-service/Dockerfile
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
      - krakend
    networks: 
      - app_network
    image: post-service:latest

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - rabbitmq
      - krakend	
    image: user-service:latest
    networks: 
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
