version: "3"

services:
  post-service:
    container_name: post-service
    build:
      context: .
      dockerfile: ./apps/post-service/Dockerfile
    restart: always
    ports:
      - 3003:3003
    networks: 
      - app_network


# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
