apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1
  template:
    metadata:
      labels:
        app: krakend
    spec:
      imagePullSecrets:
        - name: acr-credentials
      containers:
      - name: krakend
        image: asindividual.azurecr.io/krakend:3d9b0712813af2290c7c13868a79c4691225f835
        ports:
        - containerPort: 8080
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
        resources:
          requests:
            cpu: 128m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: KRAKEND_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: krakend-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30800
    protocol: TCP
  selector:
    app: krakend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: krakend-service-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: krakend-service-deployment
  minReplicas: 3
  maxReplicas: 45
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50