apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - post-service-deployment.yaml
  - user-service-deployment.yaml
  - krakend-deployment.yaml



images:
  - name: asindividual.azurecr.io/post-service
    newName: asindividual.azurecr.io/post-service
    newTag: CICD_PLACEHOLDER
  - name: asindividual.azurecr.io/user-service
    newName: asindividual.azurecr.io/user-service
    newTag: CICD_PLACEHOLDER
  - name: asindividual.azurecr.io/krakend
    newName: asindividual.azurecr.io/krakend
    newTag: CICD_PLACEHOLDER