apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        io.kompose.network/app-network: "true"
        app: user-service
    spec:
      imagePullSecrets:
        - name: acr-credentials
      containers:
        - image: asindividual.azurecr.io/user-service
          env:
            - name: RABBITMQ_URL
              value: amqp://rabbitmq:5672
          imagePullPolicy: IfNotPresent
          name: user-service
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service-k8s
spec:
  type: ClusterIP
  ports:
    - name: "user-service-port"
      port: 8082
      targetPort: 8082
  selector:
    app: user-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50